"""Add expiry notification columns to subscribed_users

Revision ID: 76bdd302dd23
Revises: a1b2c3d4e5f6
Create Date: 2025-12-16 18:01:02.358686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76bdd302dd23'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribed_users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expiry_notification_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('expiry_notification_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscribed_users', schema=None) as batch_op:
        batch_op.drop_column('expiry_notification_sent_at')
        batch_op.drop_column('expiry_notification_sent')

    # ### end Alembic commands ###
